/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author andres
 */
public class Calculadora extends javax.swing.JFrame {

    public float num1, num2;
    public String operador;
    
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        this.setTitle("Calculadora");
    }
    
    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("images/sigma.png"));


       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new javax.swing.JPanel();
        porcentaje = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        limpiar1 = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        masMenos = new javax.swing.JButton();
        unoSobreX = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        panel = new javax.swing.JLabel();
        panel2 = new javax.swing.JLabel();
        mdOscuro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setResizable(false);

        fondo1.setBackground(new java.awt.Color(23, 24, 26));

        porcentaje.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        porcentaje.setText("%");
        porcentaje.setContentAreaFilled(false);
        porcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        porcentaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        porcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btnPress.png"))); // NOI18N
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        dividir.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        dividir.setForeground(new java.awt.Color(255, 255, 255));
        dividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        dividir.setText("/");
        dividir.setContentAreaFilled(false);
        dividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dividir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        dividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue_press.png"))); // NOI18N
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        multiplicar.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        multiplicar.setForeground(new java.awt.Color(255, 255, 255));
        multiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        multiplicar.setText("x");
        multiplicar.setContentAreaFilled(false);
        multiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplicar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        multiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue_press.png"))); // NOI18N
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        restar.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        restar.setForeground(new java.awt.Color(255, 255, 255));
        restar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        restar.setText("-");
        restar.setContentAreaFilled(false);
        restar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        restar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue_press.png"))); // NOI18N
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });

        siete.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        siete.setForeground(new java.awt.Color(41, 168, 255));
        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        siete.setText("7");
        siete.setContentAreaFilled(false);
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        siete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        ocho.setForeground(new java.awt.Color(41, 168, 255));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        ocho.setText("8");
        ocho.setContentAreaFilled(false);
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ocho.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        ocho.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        nueve.setForeground(new java.awt.Color(41, 168, 255));
        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        nueve.setText("9");
        nueve.setContentAreaFilled(false);
        nueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nueve.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        nueve.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        sumar.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        sumar.setForeground(new java.awt.Color(255, 255, 255));
        sumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue_large.png"))); // NOI18N
        sumar.setText("+");
        sumar.setContentAreaFilled(false);
        sumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sumar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue.png"))); // NOI18N
        sumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_blue_large_press.png"))); // NOI18N
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        cinco.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        cinco.setForeground(new java.awt.Color(41, 168, 255));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cinco.setText("5");
        cinco.setContentAreaFilled(false);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cinco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cinco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        cuatro.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        cuatro.setForeground(new java.awt.Color(41, 168, 255));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cuatro.setText("4");
        cuatro.setContentAreaFilled(false);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuatro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cuatro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        seis.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        seis.setForeground(new java.awt.Color(41, 168, 255));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        seis.setText("6");
        seis.setContentAreaFilled(false);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seis.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        seis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        uno.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        uno.setForeground(new java.awt.Color(41, 168, 255));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        uno.setText("1");
        uno.setContentAreaFilled(false);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        uno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        tres.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        tres.setForeground(new java.awt.Color(41, 168, 255));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        tres.setText("3");
        tres.setContentAreaFilled(false);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tres.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        tres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        dos.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        dos.setForeground(new java.awt.Color(41, 168, 255));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        dos.setText("2");
        dos.setContentAreaFilled(false);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        dos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        cero.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        cero.setForeground(new java.awt.Color(41, 168, 255));
        cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cero.setText("0");
        cero.setContentAreaFilled(false);
        cero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        cero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        decimal.setForeground(new java.awt.Color(41, 168, 255));
        decimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        decimal.setText(".");
        decimal.setContentAreaFilled(false);
        decimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        decimal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black.png"))); // NOI18N
        decimal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_black_press.png"))); // NOI18N
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_large.png"))); // NOI18N
        resultado.setText("=");
        resultado.setContentAreaFilled(false);
        resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_largo.png"))); // NOI18N
        resultado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_large_press.png"))); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        limpiar1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        limpiar1.setForeground(new java.awt.Color(255, 255, 255));
        limpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.png"))); // NOI18N
        limpiar1.setContentAreaFilled(false);
        limpiar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limpiar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.png"))); // NOI18N
        limpiar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back_png.png"))); // NOI18N
        limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar1ActionPerformed(evt);
            }
        });

        potencia.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        potencia.setForeground(new java.awt.Color(255, 255, 255));
        potencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        potencia.setText("^");
        potencia.setContentAreaFilled(false);
        potencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        potencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        potencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btnPress.png"))); // NOI18N
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        raiz.setFont(new java.awt.Font("Liberation Sans", 1, 19)); // NOI18N
        raiz.setForeground(new java.awt.Color(255, 255, 255));
        raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        raiz.setText("RA");
        raiz.setContentAreaFilled(false);
        raiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        raiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btnPress.png"))); // NOI18N
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });

        masMenos.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        masMenos.setForeground(new java.awt.Color(41, 168, 255));
        masMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus_minus.png"))); // NOI18N
        masMenos.setContentAreaFilled(false);
        masMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        masMenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus_minus.png"))); // NOI18N
        masMenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus_minus_press.png"))); // NOI18N
        masMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masMenosActionPerformed(evt);
            }
        });

        unoSobreX.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        unoSobreX.setForeground(new java.awt.Color(255, 255, 255));
        unoSobreX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        unoSobreX.setText("1/x");
        unoSobreX.setContentAreaFilled(false);
        unoSobreX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unoSobreX.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btn.png"))); // NOI18N
        unoSobreX.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mdn_btnPress.png"))); // NOI18N
        unoSobreX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoSobreXActionPerformed(evt);
            }
        });

        btnAc.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        btnAc.setForeground(new java.awt.Color(255, 255, 255));
        btnAc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_ac.png"))); // NOI18N
        btnAc.setContentAreaFilled(false);
        btnAc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAc.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_grey.png"))); // NOI18N
        btnAc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn_ac_press.png"))); // NOI18N
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setFont(new java.awt.Font("Century Gothic", 0, 52)); // NOI18N
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        panel2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        mdOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/DarkModeEnable.png"))); // NOI18N
        mdOscuro.setContentAreaFilled(false);
        mdOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdOscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo1Layout.createSequentialGroup()
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondo1Layout.createSequentialGroup()
                                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondo1Layout.createSequentialGroup()
                                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(fondo1Layout.createSequentialGroup()
                                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fondo1Layout.createSequentialGroup()
                                        .addComponent(unoSobreX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fondo1Layout.createSequentialGroup()
                                        .addComponent(limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(restar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mdOscuro)))
                .addGap(18, 18, 18))
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mdOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unoSobreX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());

        this.panel.setText("="+sinCero((float) Math.sqrt(this.num1)));
        this.panel2.setText("sqrt("+sinCero(this.num1)+")");
    }//GEN-LAST:event_raizActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.operador = "^";
        this.panel.setText("");
        this.panel2.setText(this.panel2.getText()+"^");
    }//GEN-LAST:event_potenciaActionPerformed

    private void limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar1ActionPerformed
        String cadena1 = panel.getText();
        String cadenaOp = panel2.getText();
        
        cadena1 = cadena1.substring(0, cadena1.length()-1);
        System.out.println(cadena1.length());
        
        
        
        this.panel.setText(cadena1);
        
        
        
        char ultimo = cadenaOp.charAt(cadenaOp.length()-1);
        
        String ultimocaracter = Character.toString(ultimo);
        if(ultimocaracter != "+" || ultimocaracter != "-" || ultimocaracter != "x" || ultimocaracter != "/" || ultimocaracter != "^"){
            cadenaOp = cadenaOp.substring(0, cadenaOp.length()-1);
            this.panel2.setText(cadenaOp);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_limpiar1ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        this.num2 = Float.parseFloat(this.panel.getText());
        switch(this.operador){
            case "+":
            this.panel.setText("="+sinCero(this.num1+this.num2));
            
            //this.panel2.setText(this.panel2.getText()+" = "+(sinCero(this.num1+this.num2)));
            break;

            case "-":
            this.panel.setText("="+sinCero(this.num1-this.num2));
            
            //this.panel2.setText(this.panel2.getText()+" = "+(sinCero(this.num1-this.num2)));
            break;

            case "*":
            this.panel.setText("="+sinCero(this.num1*this.num2));
            
            //this.panel2.setText(this.panel2.getText()+" = "+(sinCero(this.num1*this.num2)));
            break;

            case "^":
            this.panel.setText("="+sinCero((float) Math.pow(this.num1, this.num2)));
            
            //this.panel2.setText(this.panel2.getText()+" = "+(Math.pow(this.num1, this.num2)));
            break;

            case "/":
            this.panel.setText("="+sinCero(this.num1/this.num2));
            //this.panel2.setText(this.panel2.getText()+" = "+(sinCero(this.num1/this.num2)));
            break;
        }
    }//GEN-LAST:event_resultadoActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        if(!(this.panel.getText().contains("."))){//si no contiene un punto, se pondra uno
            this.panel.setText(this.panel.getText()+".");
            this.panel2.setText(this.panel2.getText()+".");
        }
        
        
    }//GEN-LAST:event_decimalActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        this.panel.setText(this.panel.getText()+"0");
        this.panel2.setText(this.panel2.getText()+"0");
    }//GEN-LAST:event_ceroActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        this.panel.setText(this.panel.getText()+"2");
        this.panel2.setText(this.panel2.getText()+"2");
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        this.panel.setText(this.panel.getText()+"3");
        this.panel2.setText(this.panel2.getText()+"3");
    }//GEN-LAST:event_tresActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        this.panel.setText(this.panel.getText()+"1");
        this.panel2.setText(this.panel2.getText()+"1");
    }//GEN-LAST:event_unoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        this.panel.setText(this.panel.getText()+"6");
        this.panel2.setText(this.panel2.getText()+"6");
    }//GEN-LAST:event_seisActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        this.panel.setText(this.panel.getText()+"4");
        this.panel2.setText(this.panel2.getText()+"4");
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        this.panel.setText(this.panel.getText()+"5");
        this.panel2.setText(this.panel2.getText()+"5");
    }//GEN-LAST:event_cincoActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.operador = "+";
        this.panel.setText("");
        this.panel2.setText(this.panel2.getText()+"+");
    }//GEN-LAST:event_sumarActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        this.panel.setText(this.panel.getText()+"9");
        this.panel2.setText(this.panel2.getText()+"9");
    }//GEN-LAST:event_nueveActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        this.panel.setText(this.panel.getText()+"8");
        this.panel2.setText(this.panel2.getText()+"8");
    }//GEN-LAST:event_ochoActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        this.panel.setText(this.panel.getText()+"7");
        this.panel2.setText(this.panel2.getText()+"7");
    }//GEN-LAST:event_sieteActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.operador = "-";
        this.panel.setText("");
        this.panel2.setText(this.panel2.getText()+"-");
    }//GEN-LAST:event_restarActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.operador = "*";
        this.panel.setText("");
        this.panel2.setText(this.panel2.getText()+"x");
    }//GEN-LAST:event_multiplicarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.operador = "/";
        this.panel.setText("");
        this.panel2.setText(this.panel2.getText()+"/");
    }//GEN-LAST:event_dividirActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        
        this.panel.setText("="+sinCero((float) (this.num1/100)));  
        this.panel2.setText(this.panel2.getText()+"/100");
    }//GEN-LAST:event_porcentajeActionPerformed

    private void masMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masMenosActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        
        this.panel.setText(sinCero((float) (this.num1*(-1))));
        this.panel2.setText(sinCero((float) (this.num1*(-1))));
    }//GEN-LAST:event_masMenosActionPerformed

    private void unoSobreXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoSobreXActionPerformed
        this.num1 = Float.parseFloat(this.panel.getText());
        this.panel.setText("="+sinCero((float) (1/this.num1)));
        this.panel2.setText("1/("+sinCero(this.num1)+")");
    }//GEN-LAST:event_unoSobreXActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        this.panel.setText("");
        this.panel2.setText("");
    }//GEN-LAST:event_btnAcActionPerformed

    boolean darkMode = false;
    private void mdOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdOscuroActionPerformed
        if(!darkMode){
            fondo1.setBackground(Color.decode("#F7F8FB"));
            panel.setForeground(Color.decode("#424242"));
            panel2.setForeground(Color.decode("#424242"));
            masMenos.setIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus_white.png")));
            masMenos.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus_white.png")));
            masMenos.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus_white_press.png")));
            
            btnAc.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac_white.png")));
            btnAc.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac_white.png")));
            btnAc.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac_white_press.png")));
            
            limpiar1.setIcon(new ImageIcon(getClass().getResource("/imgs/back_white.png")));
            limpiar1.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/back_white.png")));
            limpiar1.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/back_white_press.png")));
            
            sumar.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_light_large.png")));
            sumar.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_light_large.png")));
            sumar.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_light_large_press.png")));
            sumar.setForeground(Color.decode("#109DFF"));
            
            resultado.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_result.png")));
            resultado.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_result.png")));
            resultado.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_result_press.png")));
            resultado.setForeground(Color.decode("#B2DAFF"));
            
            mdOscuro.setIcon(new ImageIcon(getClass().getResource("/imgs/DarkModeDisable.png")));
            
            cambiarColorBtnBlancos(cero);
            cambiarColorBtnBlancos(uno);
            cambiarColorBtnBlancos(dos);
            cambiarColorBtnBlancos(tres);
            cambiarColorBtnBlancos(cuatro);
            cambiarColorBtnBlancos(cinco);
            cambiarColorBtnBlancos(seis);
            cambiarColorBtnBlancos(siete);
            cambiarColorBtnBlancos(ocho);
            cambiarColorBtnBlancos(nueve);
            cambiarColorBtnBlancos(decimal);
            //cambiar botones operaciones
            cambiarColorBtnOps(restar);
            cambiarColorBtnOps(multiplicar);
            cambiarColorBtnOps(dividir);
            //botones superiores
            cambiarBtnSpr(unoSobreX);
            cambiarBtnSpr(raiz);
            cambiarBtnSpr(unoSobreX);
            cambiarBtnSpr(potencia);
            cambiarBtnSpr(porcentaje);
            
            darkMode = true;
        } else {
            fondo1.setBackground(Color.decode("#17181A"));
            panel.setForeground(Color.decode("#FFFFFF"));
            panel2.setForeground(Color.decode("#FFFFFF"));
            masMenos.setIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus.png")));
            masMenos.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus.png")));
            masMenos.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/plus_minus_press.png")));
            
            btnAc.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac.png")));
            btnAc.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac.png")));
            btnAc.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_ac_press.png")));
            
            limpiar1.setIcon(new ImageIcon(getClass().getResource("/imgs/back.png")));
            limpiar1.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/back.png")));
            limpiar1.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/back_png.png")));
            
            resultado.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_large.png")));
            resultado.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_large.png")));
            resultado.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_large_press.png")));
            resultado.setForeground(Color.decode("#FFFFFF"));
            
            sumar.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_large.png")));
            sumar.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_large.png")));
            sumar.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_large_press.png")));
            sumar.setForeground(Color.decode("#FFFFFF"));
            
            mdOscuro.setIcon(new ImageIcon(getClass().getResource("/imgs/DarkModeEnable.png")));
            
            cambiarColorBtnNegros(cero);
            cambiarColorBtnNegros(uno);
            cambiarColorBtnNegros(dos);
            cambiarColorBtnNegros(tres);
            cambiarColorBtnNegros(cuatro);
            cambiarColorBtnNegros(cinco);
            cambiarColorBtnNegros(seis);
            cambiarColorBtnNegros(siete);
            cambiarColorBtnNegros(ocho);
            cambiarColorBtnNegros(nueve);
            cambiarColorBtnNegros(decimal);
            
            //cambiar botones operaciones
            cambiarColorBtnOpsNegros(restar);
            cambiarColorBtnOpsNegros(multiplicar);
            cambiarColorBtnOpsNegros(dividir);
            //botones superiores
            
            cambiarBtnSprNegros(unoSobreX);
            cambiarBtnSprNegros(raiz);
            cambiarBtnSprNegros(unoSobreX);
            cambiarBtnSprNegros(potencia);
            cambiarBtnSprNegros(porcentaje);
            
            darkMode = false;
        }
        
    }//GEN-LAST:event_mdOscuroActionPerformed

    
    public String sinCero(float result){
        String retorno="";
        
        retorno = Float.toString(result);
        
        if(result %1==0){
            retorno = retorno.substring(0, retorno.length()-2);
        }
        
        return retorno;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    public void cambiarColorBtnBlancos(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_white.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_white.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_white_press.png")));
        btn.setForeground(Color.decode("#38B9FF"));
    }
    
    public void cambiarColorBtnNegros(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_black.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_black.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_black_press.png")));
        btn.setForeground(Color.decode("#29A8FF"));
    }
    
    //**********************************
    
    public void cambiarColorBtnOps(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_blueLight.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_blueLight.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_blueLight_press.png")));
        btn.setForeground(Color.decode("#109DFF"));
    }
    
    public void cambiarColorBtnOpsNegros(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/btn_blue_press.png")));
        btn.setForeground(Color.decode("#FFFFFF"));
    }
    
    //**********************************
    
    public void cambiarBtnSpr(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btn_light.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btn_light.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btn_light_press.png")));
        btn.setForeground(Color.decode("#38B9FF"));
    }
    
    
    public void cambiarBtnSprNegros(JButton btn){
        btn.setIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btn.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btn.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/imgs/mdn_btnPress.png")));
        btn.setForeground(Color.decode("#FFFFFF"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAc;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton decimal;
    private javax.swing.JButton dividir;
    private javax.swing.JButton dos;
    private javax.swing.JPanel fondo1;
    private javax.swing.JButton limpiar1;
    private javax.swing.JButton masMenos;
    private javax.swing.JButton mdOscuro;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel panel2;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton potencia;
    private javax.swing.JButton raiz;
    private javax.swing.JButton restar;
    private javax.swing.JButton resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton sumar;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    private javax.swing.JButton unoSobreX;
    // End of variables declaration//GEN-END:variables
}
